services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_management_system
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./docker/apache/sites-available/000-default-le-ssl.conf:/etc/apache2/sites-available/000-default-le-ssl.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inventory_management_system_db
    restart: always
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
